### ISSUE TITLE
Glassy streets

### ISSUE THREAD

**Issue by Avendorz** [AeroWidescreen/NFSU2HDReflections#1]
Hey Aero,

I'm torn apart by either using ImproveReflectionLOD=1 or =2.
=1 doesn't look that glassy but has less details and looks generally worse and it's the opposite with =2.
Do you think it would be possible to reduce the glassy appearance of the streets by reducing the brightness of the reflections?

Greets
Avendorz
![Screenshot (1)](https://user-images.githubusercontent.com/46428068/58384010-24002500-7fdd-11e9-99f3-dc2733c0649f.png)
![Screenshot (2)](https://user-images.githubusercontent.com/46428068/58384012-2c586000-7fdd-11e9-921d-67f6d8849af4.png)

**Comment by AeroWidescreen** [comment]
> Do you think it would be possible to reduce the glassy appearance of the streets by reducing the brightness of the reflections?

I can. I'll see about adding it in the next update.

![RoadReflBright](https://i.imgur.com/6uvvHMb.gif)

In the meanwhile, you can also lower the resolution of the road reflections. I added a feature for this in v1.2.1. Try `RoadScale = 0.25`. This will make them look the same as they do without HD Reflections, but with the improved LOD.

![RoadReflRes](https://i.imgur.com/848sIV8.png)

**Comment by AeroWidescreen** [comment]
> Do you think it would be possible to reduce the glassy appearance of the streets by reducing the brightness of the reflections?

I can sort of do that. I'll see what I can do for the next update.

![RoadReflBright](https://i.imgur.com/6uvvHMb.gif)

In the meanwhile, you can also lower the resolution of the road reflections. I added a feature for this in v1.2.1. Try `RoadScale = 0.25`. This will make them look the same as they do without HD Reflections, but with the improved LOD.

![RoadReflRes](https://i.imgur.com/848sIV8.png)

**Comment by Avendorz** [comment]
Thanks for the reply!
Yeah, I think if we play around a bit with the brightness, we could manage to make it look more realistic.
I'll give the resolution thing a try although that would make the mod only half as good. ^^

Btw: If you need someone for testing, I'll happily help you out.

**Comment by Avendorz** [comment]
Hey Aero,

how's it looking regarding the brightness?

**Comment by AeroWidescreen** [comment]
Sorry for the late reply. I haven't had a chance to look at anything, I've been too busy with other projects. I'll see what I can do this weekend.

**Comment by AeroWidescreen** [comment]
Unfortunately I still haven't found anything. What I did in my screenshot was make the reflection blur darker, which also affects the visibility of the blur itself. I was hoping I could find RGBA adjustments like I did for the mirror in Most Wanted, but so far no luck.

**Comment by Avendorz** [comment]
Hi Aero,

thanks for checking it out.
Maybe the best solution is to use 0.5 or 0.75 reflection resolution.
That way it doesn't seem so flat and mirroring.
