### ISSUE TITLE
Not compatible with ReShade Mxao

### ISSUE THREAD

**Issue by Poponardo** [AeroWidescreen/NFSU2HDReflections#2]
Can this be fixed? I mean Mxao works great with original reflections, but with HDReflections it get that shader on the reflection. Thanks.

**Comment by AeroWidescreen** [comment]
Nope, there's nothing I can do about that on my end as far as I know. Either use a lower road reflection resolution (RoadScale = 0.25) or disable ImproveReflectionLOD.
