### ISSUE TITLE
Ini values and description

### ISSUE THREAD

**Issue by Avendorz** [AeroWidescreen/NFSU2HDReflections#4]
Hey Aero,

I was wondering what the difference between HDReflections and RoadScale/VehicleScale is?
Could you also please tell me the default values of the reflections and stuff without your mod?
I think you said earlier that RoadScale/VehicleScale was 0.25 by default.

I'm basically asking because I'm having fps issues without my gpu being anywhere near maxing out. Disabling the extended render distance already helped out a lot.

Would be cool if you could give me some additional infos to the ini descriptions!

Thanks

Aven

**Comment by AeroWidescreen** [comment]
> I was wondering what the difference between HDReflections and RoadScale/VehicleScale is?

`HDReflections = 0` will use the original reflection resolution and ignore any values in the `[RESOLUTION]` section. This feature disables any modifications made to the reflection resolution.

> Could you also please tell me the default values of the reflections and stuff without your mod?

With `HDReflections = 0`

Road Reflection Res = 320x240
Vehicle Reflection Res = 256x256
Rearview Mirror Res = 256x128

---

With `HDReflections = 1`
if `ResolutionX `and `ResolutionY` = 1920x1080

Road Reflection Res = (1920x1080 × RoadScale)
Vehicle Reflection Res = (1080x1080 × VehicleScale)
Rearview Mirror Res = (1080x360 × MirrorScale)

---

So this is where you have to do some basic math. For example, at 1920x1080, `RoadScale = 0.25` would give you this:

1920 × 0.25 = 480 
1080 × 0.25 = 270
Road Reflection Res = 480x270

**Comment by AeroWidescreen** [comment]
> I was wondering what the difference between HDReflections and RoadScale/VehicleScale is?

`HDReflections = 0` will use the original reflection resolution and ignore any values in the `[RESOLUTION]` section. This feature disables any modifications made to the reflection resolution, including scale.

> Could you also please tell me the default values of the reflections and stuff without your mod?

With `HDReflections = 0`

Road Reflection Res = 320x240
Vehicle Reflection Res = 256x256
Rearview Mirror Res = 256x128

---

With `HDReflections = 1`
if `ResolutionX `and `ResolutionY` = 1920x1080

Road Reflection Res = (1920x1080 × RoadScale)
Vehicle Reflection Res = (1080x1080 × VehicleScale)
Rearview Mirror Res = (1080x360 × MirrorScale)

---

So this is where you have to do some basic math. For example, at 1920x1080, `RoadScale = 0.25` would give you this:

1920 × 0.25 = 480 
1080 × 0.25 = 270
Road Reflection Res = 480x270

**Comment by Avendorz** [comment]
Thanks Aero! 😃
